#!/bin/sh

echo "Running pre-commit checks..."

if git diff --cached --name-only | grep -E '\.env$' >/dev/null; then
    echo "ERROR: .env file detected in commit! Remove it before committing."
    exit 1
fi

if git diff --cached --name-only | grep -E '\.log$' >/dev/null; then
    echo "ERROR: Log files (.log) should not be committed."
    exit 1
fi

JS_FILES=$(git diff --cached --name-only -- '*.js')

if [ ! -z "$JS_FILES" ]; then
    echo "Checking JS formatting..."

    for file in $JS_FILES; do
        npx prettier --write "$file"
        git add "$file"
    done

    echo "JS files formatted."
fi

echo "Pre-commit checks passed!"
exit 0
