import "./globals.css";
import Navbar from '../../components/ui/Navbar.jsx';
import Sidebar from '../../components/ui/Sidebar.jsx';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white flex flex-row">
        <Sidebar />
        <Navbar />
      </body>
    </html>
  );
}
